<?php
/**
 * @var \Magento\Backend\Block\Template $block
 * @var \Creatuity\AIContentMassAction\ViewModel\AiContentEntryViewModel $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */
$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
?>

<?php if (!$viewModel->isQueueEmpty() && !$product): ?>
    <div class="messages">
        <div class="message message-notice">
            <div>
                <?= $escaper->escapeHtml(
                    __('You have walked through all the products. To start over just close the modal and open it again.')
                ) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($viewModel->isQueueEmpty()): ?>
<div class="messages">
    <div class="message message-notice">
        <div>
            <?= $escaper->escapeHtml(
                __('All queue entries have been processed and queue is empty now.')
            ) ?>
        </div>
    </div>
</div>
<?php endif; ?>